version: "2"

checks:
  argument-count:
    enabled: false

  complex-logic:
    enabled: false

  file-lines:
    enabled: false

  identical-code:
    enabled: true

  method-complexity:
    enabled: false

  method-count:
    enabled: false

  method-lines:
    enabled: false

  nested-control-flow:
    enabled: false

  return-statements:
    enabled: false

  similar-code:
    enabled: true
 
plugins:
  bundler-audit:
    enabled: true

  csslint:
    enabled: true
 
  duplication:
    enabled: true

    config:
      languages:
        javascript:
          mass_threshold: 1000

        ruby:
          mass_threshold: 80

    exclude_patterns:
      - "spec/**/*"
      - "**/eslint-config/index.js"

  eslint:
    enabled: false

  fixme:
    enabled: true

  grep:
    enabled: true

    config:
      patterns:
        no-trailing-whitespace:
          pattern: \s*$
          annotation: "Do not leave trailing whitespace"
          severity: minor
          categories: Style

        no-tabs:
          pattern: "	"
          annotation: "Do not use hard tabs"
          severity: minor
          categories: Style

    exclude_patterns:
      - "**/*/locales/*.yml"
      - "**/*/*.svg"

  stylelint:
    # FIXME: after the webpacker packages changes, this is broken with this error:
    #
    # > Error: Could not find "@decidim/stylelint-config". Do you need a `configBasedir`?
    # > See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.
    #
    # Disabling it for the moment, we should enable it as it is useful.
    #
    enabled: false

exclude_patterns:
  - "**/vendor/"
  - "node_modules/"
  - "development_app/"
  - "spec/decidim_dummy_app/"
  - "coverage/"
  - "webpack.report.html"
