name: "[CI] Test"

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  RUBY_VERSION: 3.0.6

jobs:
  test-report:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup Database
        run: bundle exec rake test_app
    
      - name: Precompile assets
        run: |
          cd spec/decidim_dummy_app
          bundle exec rails assets:precompile
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: dummy

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rspec

      - uses: actions/upload-artifact@v2-preview
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
